### ISSUE TITLE
*-wp.zip file for January and Februrary 2024?

### ISSUE THREAD

**Issue by johnbraisted** [wikipathways/wikipathways-data-release#3]
Hi, I'm not sure if this is an issue or a policy change but the two most recent data updates (monthly) have only the *-authors.zip file in the 'rdf' directory. I'm looking for the /rdf/*-wp.zip files that contains the format /wp/<species_directory>, where each species directory has a set of ttl format files. 

Will these continue to be offered. They seem like the most comprehensive file format. 
Thank you for the great resource.

Best,
John

**Comment by khanspers** [comment]
Answered here: https://github.com/wikipathways/wikipathways-help/discussions/110

**Comment by johnbraisted** [comment]
Thank you. Yes. Sorry for the duplicate. Closing the issue.
